function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("click") and action.pressed then 
		if gui.pick_node(gui.get_node("easy-mode-button"), action.x, action.y) then 
			msg.post("main:/loader#loader", "level_finished", { difficulty = 1 })
		elseif gui.pick_node(gui.get_node("hard-mode-button"), action.x, action.y) then
			msg.post("main:/loader#loader", "level_finished", { difficulty = 2 })
		end
	end
end
