local function update_gui(self)
	local node = gui.get_node("score")
	gui.set_text(node, tostring(self.score))
end

function init(self)
	self.score = 0
end

function on_message(self, message_id, message, sender)
	if message_id == hash("reset_score") then
		self.score = 0
		update_gui(self)
		print("reset score")
	elseif message_id == hash("add_score") then
		self.score = self.score + 1
		update_gui(self)
		print("score=", self.score)
	end
end