local settings = require("00_common.modules.settings")

local screen_width = settings.screen_width
local screen_height = settings.screen_height

function init(self)
	local position = vmath.vector3()
	position.x = math.random(screen_width / 5, screen_width * 4 / 5)
	position.y = math.random(screen_height * 2 / 5, screen_height * 4 / 5)
	position.z = 1.0 - (position.y / screen_height)
	go.set_position(position)
end